name: Deploy WordPress Theme via FTP

on:
  push:
    branches:
      - staging  # o la rama que utilices para producción

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Carpeta raíz del repositorio
          server-dir: ${{ secrets.FTP_REMOTE_DIR_STAGING }}  # Carpeta remota en el servidor FTP
